### PR TITLE
MBS-7909: Fix backup

### PR DESCRIPTION
**Pull request by sh-csg**

### CODE REVIEW

**Review by PhMemmel — COMMENTED** [review]
Tested:

- Confirmed that the issue is existing by backup and restore as admin including anonymized user data.
- With patch: Backup/Restore now works properly.

Occured while testing:

One (out of 2 strangely) of the kanban activities in the restored course now display an error message:
```
Error: mdb->get_record() found more than one record!
line 1691 of /lib/dml/moodle_database.php: call to debugging()
line 1651 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
line 1630 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 78 of /mod/kanban/view.php: call to moodle_database->get_record()
```
I am not 100% sure this is related, but I can reproduce this by restoring the backuped file which was created WITH the patch applied. The activitiy has personal boards enabled, but no group mode.

In fact I can confirm that the table `kanban_board` contains multiple boards all with userid=0 and template=0 which - as far as I understood the structure - should not happen.

Please fix :-)

**Comment by sh-csg** [comment]
Mapping of userid was broken (maybe occurred when changing database columns from "user" to "userid") and therefore userid was reset to 0, resulting in a second "shared board". Should work now.

**Review by PhMemmel — COMMENTED** [review]
Change looks good.

Another thing:

When backing up a course and restoring it including user information, a card containing an attachment loses its attachment. This is probably not intended?

**Comment by sh-csg** [comment]
Fixed now

**Review by PhMemmel — APPROVED** [review]
While reviewing, testing and after discussing internally a few other bugs have been fixed. Thanks und gj @sh-csg!

**Pull request merged**
